### ISSUE TITLE
Window, Door & Multigroup Crash

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tools#148]
**Describe the bug**
Adding a window, door or multigroup causes blender to crash. Use provided blend file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the blend file in blender.
2. Ensure add-on is enabled.
3. Create a window, door or multigroup on the already selected face.
4. See error/crash.

**Expected behaviour**
No crash.

**Screenshots**
### Window Crash
```python
Traceback (most recent call last):
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/utils/util_common.py", line 68, in inner
    return func(*args, **kwargs)
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/core/window/window.py", line 23, in build
    if create_window(bm, faces, prop):
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/core/window/window_types.py", line 46, in create_window
    face = create_window_split(bm, aface, prop.size_offset.size, prop.size_offset.offset)
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/utils/util_material.py", line 59, in wrapper
    result = func(*args, **kwargs)
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/core/window/window_types.py", line 68, in create_window_split
    return v_faces[1]
IndexError: list index out of range
```

### Door Crash
```python
Traceback (most recent call last):
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/utils/util_common.py", line 68, in inner
    return func(*args, **kwargs)
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/core/door/door.py", line 24, in build
    if create_door(bm, faces, props):
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/core/door/door_types.py", line 45, in create_door
    face = create_door_split(bm, aface, prop)
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/utils/util_material.py", line 59, in wrapper
    result = func(*args, **kwargs)
  File "/home/ranjian0/.config/blender/2.82/scripts/addons/building_tools/core/door/door_types.py", line 66, in create_door_split
    return v_faces[0]
IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - OS: any
 - Blender Version any
 - Addon Version any

**Additional context**
Blend File: 
[Add_Floors_Window_Door_Multigroup_-_crash.zip](https://github.com/ranjian0/building_tools/files/4886934/Add_Floors_Window_Door_Multigroup_-_crash.zip)

Reported by user **JS** on discord.

**Comment by ranjian0** [comment]
Likely regression from e907fc2

**Comment by berkaltug** [comment]
I have faced same issue too.It keeps crashing at random moments while adding door or windows.On blender 2.83 ubuntu 18.

**Comment by ranjian0** [comment]
I am working on a solution.
