### ISSUE TITLE
Use externally imported models to increase the window will crash

### ISSUE THREAD

**Issue by zenbbbb** [ranjian0/building_tools#162]
Using an externally imported model to increase the window will crash. The same problem will occur in DEA and FBX formats, and the same problem on other computers.
model https://1drv.ms/u/s!AkHZp2ZWp8xXj3GFmfqatm34XfKf?e=KJdDbs
           https://youtu.be/Vgs1_OJl1VI

**Comment by MCrafterzz** [comment]
To increase the window? What do you mean with that?

**Comment by zenbbbb** [comment]
Operation video at this link：    https://youtu.be/Vgs1_OJl1VI

**Comment by MCrafterzz** [comment]
> Operation video at this link： https://youtu.be/Vgs1_OJl1VI

If you could take a picture of the console then that would be extremely helpful

Windows > Toggle System Console

**Comment by ranjian0** [comment]
In your video, it looks like the array count snaps to a high number very quickly.  As @MCrafterzz  has mentioned, it would be great to see the output from your console. 

Also, when any element(door/window etc) is forced to reduce its width due to array count being too high, if the array count is later reduced, the addon does not resize the element. That's why the window are soo thin afterwards. I tried to solve this a while ago but it was not trivial.

**Comment by ranjian0** [comment]
This is the log from my crash
```python
Traceback (most recent call last):
  File "/home/ranjian0/.config/blender/2.83/scripts/addons/building_tools/utils/util_common.py", line 69, in inner
    return func(*args, **kwargs)
  File "/home/ranjian0/.config/blender/2.83/scripts/addons/building_tools/building/window/window.py", line 25, in build
    if create_window(bm, faces, prop):
  File "/home/ranjian0/.config/blender/2.83/scripts/addons/building_tools/building/window/window_types.py", line 45, in create_window
    face = create_window_split(bm, aface, prop.size_offset.size, prop.size_offset.offset)
  File "/home/ranjian0/.config/blender/2.83/scripts/addons/building_tools/utils/util_material.py", line 68, in wrapper
    result = func(*args, **kwargs)
  File "/home/ranjian0/.config/blender/2.83/scripts/addons/building_tools/building/window/window_types.py", line 68, in create_window_split
    return v_faces[1]
IndexError: list index out of range
```

**Comment by zenbbbb** [comment]
Hello, I recorded the crash log
https://youtu.be/fQLRXWXaHRo

**Comment by ranjian0** [comment]
Looks like its similar to my crash log. Thanks for your feedback, I'll work on a fix for this.

**Comment by fpibbs** [comment]
Same issue, only from Windows also for me.
In small words, georeferenced buildings footprints imported from Blender-OSM, will permit to construct floors or doors without problems.
For windows, if generated directly on the surface created with Blender-OSM, will crash blender.

**Comment by ranjian0** [comment]
> Same issue, only from Windows also for me.
> In small words, georeferenced buildings footprints imported from Blender-OSM, will permit to construct floors or doors without problems.
> For windows, if generated directly on the surface created with Blender-OSM, will crash blender.

A `blend` file containing your use-case would be very helpful.

**Comment by zenbbbb** [comment]
> > 同样的问题， 只有从 Windows 也对我来说。用小话来说，从 Blender-OSM 进口的地理参考建筑物脚印将允许毫无问题地建造地板或门。对于窗口，如果直接在使用 Blender-OSM 创建的表面上生成，则混合器将崩溃。
> 
> 包含用例的文件将非常有用。`blend`

型号文件： https://1drv.ms/u/s!AkHZp2ZWp8xXj3GFmfqatm34XfKf?e=KJdDbs

**Comment by fpibbs** [comment]
Please have a look to this footprint OSM georeferenced file...the problem only persists on vertical wall from footprint and only for windows...


[Italian_Town_Footprints.zip](https://github.com/ranjian0/building_tools/files/5073549/Italian_Town_Footprints.zip)
