### ISSUE TITLE
window count  error

### ISSUE THREAD

**Issue by zenbbbb** [ranjian0/building_tools#185]
Unable to increase the number of Windows when adding them
https://drive.google.com/drive/folders/1zlGuY20GsbLVM2RGwQprFMw79zOx6sMV?usp=sharing

**Comment by ranjian0** [comment]
Please provide access to the google drive

**Comment by zenbbbb** [comment]
Now you can access it

**Comment by ranjian0** [comment]
Hi, can you share the console error for this issue? I am not able to duplicate.

If you are not sure to show the console, it is at 
Window -> toggle console menu in blender for windows.

Take a screenshot of the error

**Comment by zenbbbb** [comment]
Color management: Using E:\zengbiao\imageworks-OpenColorIO-Configs-v1.0_r2-8-g0bb079c\imageworks-OpenColorIO-Configs-0bb079c\aces_1.0.1\config.ocio as a configuration file
Read prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend
Color management: display "sRGB" used by scene not found, setting to default ("ACES").
Color management: scene view "Filmic" not found, setting default "sRGB D60 sim.".
Color management: sequencer colorspace "sRGB" not found, will use default instead.
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
Color management: display "sRGB" used by scene not found, setting to default ("ACES").
Color management: scene view "Filmic" not found, setting default "sRGB D60 sim.".
Color management: sequencer colorspace "sRGB" not found, will use default instead.
drop file C:\Users\Administrator\Downloads\0511a.blend1
drop file C:\Users\Administrator\Downloads\0511a.blend1
drop file C:\Users\Administrator\Downloads\0511a.blend1
drop file C:\Users\Administrator\Downloads\0511a (1).blend
Read blend: C:\Users\Administrator\Downloads\0511a (1).blend
Color management: display "sRGB" used by scene not found, setting to default ("ACES").
Color management: scene view "Filmic" not found, setting default "sRGB D60 sim.".
Color management: sequencer colorspace "sRGB" not found, will use default instead.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build
    if create_window(bm, faces, prop):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 60, in create_window
    spread_array(bm, split_edges, split_faces, max_width, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in spread_array
    for idx, edge in enumerate(split_edges)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in <dictcomp>
    for idx, edge in enumerate(split_edges)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build
    if create_window(bm, faces, prop):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 60, in create_window
    spread_array(bm, split_edges, split_faces, max_width, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in spread_array
    for idx, edge in enumerate(split_edges)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in <dictcomp>
    for idx, edge in enumerate(split_edges)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build
    if create_window(bm, faces, prop):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 60, in create_window
    spread_array(bm, split_edges, split_faces, max_width, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in spread_array
    for idx, edge in enumerate(split_edges)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in <dictcomp>
    for idx, edge in enumerate(split_edges)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build
    if create_window(bm, faces, prop):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 60, in create_window
    spread_array(bm, split_edges, split_faces, max_width, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in spread_array
    for idx, edge in enumerate(split_edges)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in <dictcomp>
    for idx, edge in enumerate(split_edges)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build
    if create_window(bm, faces, prop):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 60, in create_window
    spread_array(bm, split_edges, split_faces, max_width, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in spread_array
    for idx, edge in enumerate(split_edges)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in <dictcomp>
    for idx, edge in enumerate(split_edges)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build
    if create_window(bm, faces, prop):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 60, in create_window
    spread_array(bm, split_edges, split_faces, max_width, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in spread_array
    for idx, edge in enumerate(split_edges)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\array.py", line 100, in <dictcomp>
    for idx, edge in enumerate(split_edges)
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 69, in add_custom_execute
    place_custom_object(context, self.props, custom_obj)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 133, in place_custom_object
    place_object_on_face(bm, split_face, custom_obj, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 207, in place_object_on_face
    transform_parallel_to_face(bm, custom_faces, face)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 257, in transform_parallel_to_face
    angle = target_normal.xy.angle_signed(custom_normal.xy)
ValueError: Vector.angle_signed(other): zero length vectors have no valid angle
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 69, in add_custom_execute
    place_custom_object(context, self.props, custom_obj)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 133, in place_custom_object
    place_object_on_face(bm, split_face, custom_obj, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 207, in place_object_on_face
    transform_parallel_to_face(bm, custom_faces, face)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 257, in transform_parallel_to_face
    angle = target_normal.xy.angle_signed(custom_normal.xy)
ValueError: Vector.angle_signed(other): zero length vectors have no valid angle
Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 68, in add_custom_execute
    apply_transforms(context, custom_obj)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 104, in apply_transforms
    bpy.context.view_layer.objects.active = obj
RuntimeError: Error: ViewLayer 'View Layer' does not contain object 'Cylinder'

Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 69, in add_custom_execute
    place_custom_object(context, self.props, custom_obj)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 133, in place_custom_object
    place_object_on_face(bm, split_face, custom_obj, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 204, in place_object_on_face
    current_size = calc_verts_bounds(custom_verts)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 217, in calc_verts_bounds
    bounds = get_bounding_verts(verts)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_mesh.py", line 359, in get_bounding_verts
    topleft, *_, topright = sorted(top_verts, key=lambda v: v.co.xy.to_tuple(3))
ValueError: not enough values to unpack (expected at least 2, got 1)
Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in inner
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 69, in add_custom_execute
    place_custom_object(context, self.props, custom_obj)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 133, in place_custom_object
    place_object_on_face(bm, split_face, custom_obj, prop)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 204, in place_object_on_face
    current_size = calc_verts_bounds(custom_verts)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\building\customobj.py", line 217, in calc_verts_bounds
    bounds = get_bounding_verts(verts)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\building_tools-master\btools\utils\util_mesh.py", line 359, in get_bounding_verts
    topleft, *_, topright = sorted(top_verts, key=lambda v: v.co.xy.to_tuple(3))
ValueError: not enough values to unpack (expected at least 2, got 1)

**Comment by zenbbbb** [comment]
https://youtu.be/XOJhifA0c-4

**Comment by ranjian0** [comment]
Thanks.
