### ISSUE TITLE
How can I solve AttributeError: '__RestrictContext' object has no attribute 'scene' problem?

### ISSUE THREAD

**Issue by Stern-Hayat** [ranjian0/building_tools#201]
Hello.

I installed your wonderful concept add-ons on my Mac, and I tried [Preferences] -> checked [Mesh: Building Tools].
Then 'AttributeError: '__RestrictContext' object has no attribute 'scene' error occurs and I cannot activate add-ons.

How can I solve the problem?

blender version: 3.0.0 
add-on version: 1.0.9

Thank you.

*error* ====================================================================================

Traceback (most recent call last):
  File "/Applications/Blender 2.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users…/Blender/3.0/scripts/addons/building_tools-master/__init__.py", line 2, in <module>
    from .btools.building.register import register_building, unregister_building
  File "/Users…/Blender/3.0/scripts/addons/building_tools-master/btools/building/register.py", line 2, in <module>
    from .arch import ArchProperty
  File "/Users…/Blender/3.0/scripts/addons/building_tools-master/btools/building/arch.py", line 26, in <module>
    class ArchProperty(bpy.types.PropertyGroup):
  File "/Users…/Blender/3.0/scripts/addons/building_tools-master/btools/building/arch.py", line 45, in ArchProperty
    min=get_scaled_unit(0.01),
  File "/Users…/Blender/3.0/scripts/addons/building_tools-master/btools/utils/util_common.py", line 146, in get_scaled_unit
    scale = bpy.context.scene.unit_settings.scale_length
AttributeError: '_RestrictContext' object has no attribute 'scene'

**Comment by ranjian0** [comment]
Try using the zip from the releases rather than the master branch. I will try to get a fix out today.
https://github.com/ranjian0/building_tools/releases/download/v1.0.9/building_tools-v1.0.9.zip
